% Solve a Clustering Problem with a Self-Organizing Map
% Script generated by NCTOOL
% Created Tue Dec 13 03:48:12 PST 2011
%
% This script assumes these variables are defined:
%
%   nn_input - input data.
load nn_input_training_data65;
load nn_output_training_data65;

inputs = nn_input';

% Create a Self-Organizing Map
dimension1 = 6;
dimension2 = 6;
net = selforgmap([dimension1 dimension2]);

% Train the Network
[net,tr] = train(net,inputs);

% Test the Network
outputs = net(inputs);

% View the Network
view(net)

% Plots
% Uncomment these lines to enable various plots.
%figure, plotsomtop(net)
%figure, plotsomnc(net)
%figure, plotsomnd(net)
%figure, plotsomplanes(net)
%figure, plotsomhits(net,inputs)
%figure, plotsompos(net,inputs)
